<?php

declare(strict_types=1);

namespace App\DataFixtures;

final class AdminNationwideListingSeedDefinitions
{
    public const ADMIN_EMAIL = 'admin@renlo.local';

    /**
     * @return list<array{
     *     citySlug: string,
     *     dealType: string,
     *     listingType: string,
     *     price: int,
     *     rooms: int,
     *     area: float,
     *     floor: int,
     *     totalFloors: int,
     *     address: string,
     *     rentTerm: string|null,
     *     verified: bool,
     *     fromOwner: bool,
     *     hasRenovation: bool,
     *     hasDeposit: bool,
     *     utilitiesIncluded: bool,
     *     noCommission: bool,
     *     latOffset: float,
     *     lngOffset: float
     * }>
     */
    public static function all(): array
    {
        return [
            ['citySlug' => 'minsk', 'dealType' => 'sale', 'listingType' => 'apartment', 'price' => 142000, 'rooms' => 2, 'area' => 56.0, 'floor' => 5, 'totalFloors' => 12, 'address' => 'ул. Тимирязева, 67', 'rentTerm' => null, 'verified' => true, 'fromOwner' => true, 'hasRenovation' => true, 'hasDeposit' => false, 'utilitiesIncluded' => false, 'noCommission' => true, 'latOffset' => 0.012, 'lngOffset' => -0.018],
            ['citySlug' => 'minsk', 'dealType' => 'rent', 'listingType' => 'apartment', 'price' => 720, 'rooms' => 3, 'area' => 78.0, 'floor' => 9, 'totalFloors' => 16, 'address' => 'пр. Дзержинского, 91', 'rentTerm' => 'long', 'verified' => true, 'fromOwner' => false, 'hasRenovation' => true, 'hasDeposit' => true, 'utilitiesIncluded' => false, 'noCommission' => false, 'latOffset' => -0.021, 'lngOffset' => 0.009],
            ['citySlug' => 'minsk', 'dealType' => 'sale', 'listingType' => 'house', 'price' => 268000, 'rooms' => 4, 'area' => 128.0, 'floor' => 2, 'totalFloors' => 2, 'address' => 'ул. Ратомская, 14', 'rentTerm' => null, 'verified' => false, 'fromOwner' => true, 'hasRenovation' => true, 'hasDeposit' => false, 'utilitiesIncluded' => false, 'noCommission' => true, 'latOffset' => 0.028, 'lngOffset' => 0.031],
            ['citySlug' => 'minsk', 'dealType' => 'rent', 'listingType' => 'room', 'price' => 240, 'rooms' => 1, 'area' => 17.0, 'floor' => 3, 'totalFloors' => 9, 'address' => 'ул. Богдановича, 55', 'rentTerm' => 'daily', 'verified' => false, 'fromOwner' => false, 'hasRenovation' => false, 'hasDeposit' => false, 'utilitiesIncluded' => true, 'noCommission' => true, 'latOffset' => 0.006, 'lngOffset' => -0.008],
            ['citySlug' => 'minsk', 'dealType' => 'sale', 'listingType' => 'commercial', 'price' => 295000, 'rooms' => 2, 'area' => 112.0, 'floor' => 1, 'totalFloors' => 5, 'address' => 'ул. Немига, 30', 'rentTerm' => null, 'verified' => true, 'fromOwner' => true, 'hasRenovation' => false, 'hasDeposit' => false, 'utilitiesIncluded' => false, 'noCommission' => false, 'latOffset' => -0.004, 'lngOffset' => 0.002],
            ['citySlug' => 'minsk', 'dealType' => 'rent', 'listingType' => 'commercial', 'price' => 1850, 'rooms' => 1, 'area' => 68.0, 'floor' => 2, 'totalFloors' => 6, 'address' => 'пр. Победителей, 3', 'rentTerm' => 'long', 'verified' => true, 'fromOwner' => false, 'hasRenovation' => true, 'hasDeposit' => true, 'utilitiesIncluded' => false, 'noCommission' => true, 'latOffset' => 0.015, 'lngOffset' => -0.011],
            ['citySlug' => 'minsk', 'dealType' => 'sale', 'listingType' => 'apartment', 'price' => 98000, 'rooms' => 1, 'area' => 38.0, 'floor' => 7, 'totalFloors' => 9, 'address' => 'ул. Притыцкого, 48', 'rentTerm' => null, 'verified' => false, 'fromOwner' => true, 'hasRenovation' => false, 'hasDeposit' => false, 'utilitiesIncluded' => false, 'noCommission' => true, 'latOffset' => -0.017, 'lngOffset' => -0.025],
            ['citySlug' => 'minsk', 'dealType' => 'rent', 'listingType' => 'apartment', 'price' => 410, 'rooms' => 2, 'area' => 52.0, 'floor' => 4, 'totalFloors' => 10, 'address' => 'ул. Ложинская, 22', 'rentTerm' => 'daily', 'verified' => true, 'fromOwner' => false, 'hasRenovation' => true, 'hasDeposit' => false, 'utilitiesIncluded' => true, 'noCommission' => false, 'latOffset' => 0.019, 'lngOffset' => 0.022],
            ['citySlug' => 'minsk', 'dealType' => 'sale', 'listingType' => 'apartment', 'price' => 188000, 'rooms' => 3, 'area' => 84.0, 'floor' => 11, 'totalFloors' => 16, 'address' => 'ул. Берута, 11', 'rentTerm' => null, 'verified' => true, 'fromOwner' => false, 'hasRenovation' => true, 'hasDeposit' => false, 'utilitiesIncluded' => false, 'noCommission' => false, 'latOffset' => -0.009, 'lngOffset' => 0.014],
            ['citySlug' => 'minsk', 'dealType' => 'rent', 'listingType' => 'house', 'price' => 1350, 'rooms' => 5, 'area' => 150.0, 'floor' => 1, 'totalFloors' => 2, 'address' => 'ул. Кольцова, 8', 'rentTerm' => 'long', 'verified' => false, 'fromOwner' => true, 'hasRenovation' => true, 'hasDeposit' => true, 'utilitiesIncluded' => false, 'noCommission' => true, 'latOffset' => 0.033, 'lngOffset' => -0.027],

            ['citySlug' => 'brest-city', 'dealType' => 'sale', 'listingType' => 'apartment', 'price' => 78000, 'rooms' => 2, 'area' => 54.0, 'floor' => 4, 'totalFloors' => 9, 'address' => 'ул. Пушкинская, 19', 'rentTerm' => null, 'verified' => true, 'fromOwner' => true, 'hasRenovation' => true, 'hasDeposit' => false, 'utilitiesIncluded' => false, 'noCommission' => true, 'latOffset' => 0.008, 'lngOffset' => -0.012],
            ['citySlug' => 'brest-city', 'dealType' => 'rent', 'listingType' => 'apartment', 'price' => 380, 'rooms' => 1, 'area' => 41.0, 'floor' => 2, 'totalFloors' => 5, 'address' => 'ул. Карбышева, 7', 'rentTerm' => 'long', 'verified' => false, 'fromOwner' => false, 'hasRenovation' => false, 'hasDeposit' => true, 'utilitiesIncluded' => true, 'noCommission' => false, 'latOffset' => -0.011, 'lngOffset' => 0.007],
            ['citySlug' => 'brest-city', 'dealType' => 'sale', 'listingType' => 'house', 'price' => 165000, 'rooms' => 4, 'area' => 110.0, 'floor' => 1, 'totalFloors' => 2, 'address' => 'ул. Орловская, 31', 'rentTerm' => null, 'verified' => true, 'fromOwner' => true, 'hasRenovation' => false, 'hasDeposit' => false, 'utilitiesIncluded' => false, 'noCommission' => false, 'latOffset' => 0.016, 'lngOffset' => 0.019],
            ['citySlug' => 'brest-city', 'dealType' => 'rent', 'listingType' => 'commercial', 'price' => 920, 'rooms' => 1, 'area' => 55.0, 'floor' => 1, 'totalFloors' => 3, 'address' => 'ул. Гоголя, 22', 'rentTerm' => 'long', 'verified' => true, 'fromOwner' => false, 'hasRenovation' => true, 'hasDeposit' => true, 'utilitiesIncluded' => false, 'noCommission' => true, 'latOffset' => -0.006, 'lngOffset' => -0.009],
            ['citySlug' => 'brest-city', 'dealType' => 'sale', 'listingType' => 'room', 'price' => 28000, 'rooms' => 1, 'area' => 16.0, 'floor' => 5, 'totalFloors' => 9, 'address' => 'ул. Московская, 62', 'rentTerm' => null, 'verified' => false, 'fromOwner' => true, 'hasRenovation' => false, 'hasDeposit' => false, 'utilitiesIncluded' => false, 'noCommission' => true, 'latOffset' => 0.004, 'lngOffset' => 0.013],

            ['citySlug' => 'vitebsk-city', 'dealType' => 'sale', 'listingType' => 'apartment', 'price' => 69000, 'rooms' => 2, 'area' => 49.0, 'floor' => 6, 'totalFloors' => 9, 'address' => 'ул. Правды, 15', 'rentTerm' => null, 'verified' => true, 'fromOwner' => false, 'hasRenovation' => true, 'hasDeposit' => false, 'utilitiesIncluded' => false, 'noCommission' => false, 'latOffset' => 0.009, 'lngOffset' => -0.014],
            ['citySlug' => 'vitebsk-city', 'dealType' => 'rent', 'listingType' => 'apartment', 'price' => 310, 'rooms' => 1, 'area' => 36.0, 'floor' => 3, 'totalFloors' => 5, 'address' => 'ул. Смоленская, 8', 'rentTerm' => 'daily', 'verified' => false, 'fromOwner' => true, 'hasRenovation' => false, 'hasDeposit' => false, 'utilitiesIncluded' => true, 'noCommission' => true, 'latOffset' => -0.013, 'lngOffset' => 0.008],
            ['citySlug' => 'vitebsk-city', 'dealType' => 'sale', 'listingType' => 'house', 'price' => 142000, 'rooms' => 3, 'area' => 98.0, 'floor' => 2, 'totalFloors' => 2, 'address' => 'ул. Чкалова, 27', 'rentTerm' => null, 'verified' => true, 'fromOwner' => true, 'hasRenovation' => true, 'hasDeposit' => false, 'utilitiesIncluded' => false, 'noCommission' => true, 'latOffset' => 0.018, 'lngOffset' => 0.021],
            ['citySlug' => 'vitebsk-city', 'dealType' => 'rent', 'listingType' => 'commercial', 'price' => 780, 'rooms' => 2, 'area' => 72.0, 'floor' => 1, 'totalFloors' => 4, 'address' => 'пр. Фрунзе, 41', 'rentTerm' => 'long', 'verified' => true, 'fromOwner' => false, 'hasRenovation' => false, 'hasDeposit' => true, 'utilitiesIncluded' => false, 'noCommission' => false, 'latOffset' => -0.007, 'lngOffset' => -0.016],
            ['citySlug' => 'vitebsk-city', 'dealType' => 'sale', 'listingType' => 'apartment', 'price' => 115000, 'rooms' => 3, 'area' => 71.0, 'floor' => 8, 'totalFloors' => 12, 'address' => 'ул. Гагарина, 50', 'rentTerm' => null, 'verified' => false, 'fromOwner' => true, 'hasRenovation' => true, 'hasDeposit' => false, 'utilitiesIncluded' => false, 'noCommission' => true, 'latOffset' => 0.011, 'lngOffset' => 0.005],

            ['citySlug' => 'gomel-city', 'dealType' => 'sale', 'listingType' => 'apartment', 'price' => 73000, 'rooms' => 2, 'area' => 53.0, 'floor' => 5, 'totalFloors' => 9, 'address' => 'ул. Крестьянская, 16', 'rentTerm' => null, 'verified' => true, 'fromOwner' => true, 'hasRenovation' => false, 'hasDeposit' => false, 'utilitiesIncluded' => false, 'noCommission' => true, 'latOffset' => 0.007, 'lngOffset' => -0.01],
            ['citySlug' => 'gomel-city', 'dealType' => 'rent', 'listingType' => 'apartment', 'price' => 350, 'rooms' => 2, 'area' => 48.0, 'floor' => 7, 'totalFloors' => 10, 'address' => 'ул. Барыкина, 121', 'rentTerm' => 'long', 'verified' => true, 'fromOwner' => false, 'hasRenovation' => true, 'hasDeposit' => true, 'utilitiesIncluded' => false, 'noCommission' => false, 'latOffset' => -0.015, 'lngOffset' => 0.012],
            ['citySlug' => 'gomel-city', 'dealType' => 'sale', 'listingType' => 'commercial', 'price' => 210000, 'rooms' => 1, 'area' => 95.0, 'floor' => 1, 'totalFloors' => 3, 'address' => 'пр. Ленина, 45', 'rentTerm' => null, 'verified' => true, 'fromOwner' => false, 'hasRenovation' => true, 'hasDeposit' => false, 'utilitiesIncluded' => false, 'noCommission' => false, 'latOffset' => 0.003, 'lngOffset' => 0.006],
            ['citySlug' => 'gomel-city', 'dealType' => 'rent', 'listingType' => 'room', 'price' => 180, 'rooms' => 1, 'area' => 15.0, 'floor' => 2, 'totalFloors' => 5, 'address' => 'ул. Советская, 61', 'rentTerm' => 'daily', 'verified' => false, 'fromOwner' => true, 'hasRenovation' => false, 'hasDeposit' => false, 'utilitiesIncluded' => true, 'noCommission' => true, 'latOffset' => -0.008, 'lngOffset' => -0.005],
            ['citySlug' => 'gomel-city', 'dealType' => 'sale', 'listingType' => 'house', 'price' => 155000, 'rooms' => 4, 'area' => 118.0, 'floor' => 1, 'totalFloors' => 2, 'address' => 'ул. Федюнинского, 9', 'rentTerm' => null, 'verified' => false, 'fromOwner' => true, 'hasRenovation' => true, 'hasDeposit' => false, 'utilitiesIncluded' => false, 'noCommission' => true, 'latOffset' => 0.02, 'lngOffset' => -0.017],

            ['citySlug' => 'grodno-city', 'dealType' => 'sale', 'listingType' => 'apartment', 'price' => 82000, 'rooms' => 2, 'area' => 57.0, 'floor' => 6, 'totalFloors' => 9, 'address' => 'ул. Дзержинского, 33', 'rentTerm' => null, 'verified' => true, 'fromOwner' => true, 'hasRenovation' => true, 'hasDeposit' => false, 'utilitiesIncluded' => false, 'noCommission' => false, 'latOffset' => 0.01, 'lngOffset' => 0.008],
            ['citySlug' => 'grodno-city', 'dealType' => 'rent', 'listingType' => 'apartment', 'price' => 390, 'rooms' => 2, 'area' => 50.0, 'floor' => 4, 'totalFloors' => 9, 'address' => 'ул. Белуша, 12', 'rentTerm' => 'long', 'verified' => false, 'fromOwner' => false, 'hasRenovation' => false, 'hasDeposit' => true, 'utilitiesIncluded' => true, 'noCommission' => true, 'latOffset' => -0.012, 'lngOffset' => -0.007],
            ['citySlug' => 'grodno-city', 'dealType' => 'sale', 'listingType' => 'house', 'price' => 178000, 'rooms' => 5, 'area' => 140.0, 'floor' => 2, 'totalFloors' => 2, 'address' => 'ул. Индурское шоссе, 5', 'rentTerm' => null, 'verified' => true, 'fromOwner' => true, 'hasRenovation' => true, 'hasDeposit' => false, 'utilitiesIncluded' => false, 'noCommission' => true, 'latOffset' => 0.022, 'lngOffset' => 0.015],
            ['citySlug' => 'grodno-city', 'dealType' => 'rent', 'listingType' => 'commercial', 'price' => 1100, 'rooms' => 1, 'area' => 80.0, 'floor' => 1, 'totalFloors' => 4, 'address' => 'ул. Советская, 25', 'rentTerm' => 'long', 'verified' => true, 'fromOwner' => false, 'hasRenovation' => true, 'hasDeposit' => true, 'utilitiesIncluded' => false, 'noCommission' => false, 'latOffset' => -0.005, 'lngOffset' => 0.011],
            ['citySlug' => 'grodno-city', 'dealType' => 'sale', 'listingType' => 'apartment', 'price' => 105000, 'rooms' => 3, 'area' => 69.0, 'floor' => 9, 'totalFloors' => 12, 'address' => 'ул. Пушкина, 41', 'rentTerm' => null, 'verified' => false, 'fromOwner' => true, 'hasRenovation' => false, 'hasDeposit' => false, 'utilitiesIncluded' => false, 'noCommission' => true, 'latOffset' => 0.014, 'lngOffset' => -0.019],

            ['citySlug' => 'mogilev-city', 'dealType' => 'sale', 'listingType' => 'apartment', 'price' => 71000, 'rooms' => 2, 'area' => 51.0, 'floor' => 3, 'totalFloors' => 9, 'address' => 'ул. Челюскинцев, 18', 'rentTerm' => null, 'verified' => true, 'fromOwner' => false, 'hasRenovation' => true, 'hasDeposit' => false, 'utilitiesIncluded' => false, 'noCommission' => false, 'latOffset' => 0.006, 'lngOffset' => -0.009],
            ['citySlug' => 'mogilev-city', 'dealType' => 'rent', 'listingType' => 'apartment', 'price' => 330, 'rooms' => 1, 'area' => 39.0, 'floor' => 5, 'totalFloors' => 9, 'address' => 'ул. Якубовского, 6', 'rentTerm' => 'long', 'verified' => true, 'fromOwner' => true, 'hasRenovation' => false, 'hasDeposit' => true, 'utilitiesIncluded' => false, 'noCommission' => true, 'latOffset' => -0.01, 'lngOffset' => 0.014],
            ['citySlug' => 'mogilev-city', 'dealType' => 'sale', 'listingType' => 'commercial', 'price' => 198000, 'rooms' => 2, 'area' => 105.0, 'floor' => 1, 'totalFloors' => 3, 'address' => 'ул. Ленинская, 29', 'rentTerm' => null, 'verified' => true, 'fromOwner' => true, 'hasRenovation' => true, 'hasDeposit' => false, 'utilitiesIncluded' => false, 'noCommission' => true, 'latOffset' => 0.002, 'lngOffset' => 0.004],
            ['citySlug' => 'mogilev-city', 'dealType' => 'rent', 'listingType' => 'house', 'price' => 890, 'rooms' => 4, 'area' => 115.0, 'floor' => 1, 'totalFloors' => 2, 'address' => 'ул. Гришина, 44', 'rentTerm' => 'long', 'verified' => false, 'fromOwner' => false, 'hasRenovation' => true, 'hasDeposit' => true, 'utilitiesIncluded' => true, 'noCommission' => false, 'latOffset' => 0.017, 'lngOffset' => -0.013],
            ['citySlug' => 'mogilev-city', 'dealType' => 'sale', 'listingType' => 'room', 'price' => 31000, 'rooms' => 1, 'area' => 18.0, 'floor' => 4, 'totalFloors' => 5, 'address' => 'ул. Мира, 23', 'rentTerm' => null, 'verified' => false, 'fromOwner' => true, 'hasRenovation' => false, 'hasDeposit' => false, 'utilitiesIncluded' => false, 'noCommission' => true, 'latOffset' => -0.014, 'lngOffset' => 0.008],

            ['citySlug' => 'borisov', 'dealType' => 'sale', 'listingType' => 'apartment', 'price' => 54000, 'rooms' => 2, 'area' => 47.0, 'floor' => 3, 'totalFloors' => 5, 'address' => 'ул. Строителей, 10', 'rentTerm' => null, 'verified' => true, 'fromOwner' => true, 'hasRenovation' => true, 'hasDeposit' => false, 'utilitiesIncluded' => false, 'noCommission' => true, 'latOffset' => 0.005, 'lngOffset' => -0.006],
            ['citySlug' => 'borisov', 'dealType' => 'rent', 'listingType' => 'apartment', 'price' => 260, 'rooms' => 1, 'area' => 34.0, 'floor' => 2, 'totalFloors' => 5, 'address' => 'ул. Днепровская, 4', 'rentTerm' => 'long', 'verified' => false, 'fromOwner' => false, 'hasRenovation' => false, 'hasDeposit' => true, 'utilitiesIncluded' => true, 'noCommission' => false, 'latOffset' => -0.007, 'lngOffset' => 0.009],
            ['citySlug' => 'borisov', 'dealType' => 'sale', 'listingType' => 'house', 'price' => 98000, 'rooms' => 3, 'area' => 90.0, 'floor' => 1, 'totalFloors' => 2, 'address' => 'ул. Лопатина, 17', 'rentTerm' => null, 'verified' => true, 'fromOwner' => true, 'hasRenovation' => false, 'hasDeposit' => false, 'utilitiesIncluded' => false, 'noCommission' => false, 'latOffset' => 0.012, 'lngOffset' => 0.011],

            ['citySlug' => 'soligorsk', 'dealType' => 'sale', 'listingType' => 'apartment', 'price' => 61000, 'rooms' => 2, 'area' => 52.0, 'floor' => 6, 'totalFloors' => 9, 'address' => 'ул. Корженевского, 13', 'rentTerm' => null, 'verified' => true, 'fromOwner' => false, 'hasRenovation' => true, 'hasDeposit' => false, 'utilitiesIncluded' => false, 'noCommission' => true, 'latOffset' => 0.004, 'lngOffset' => -0.008],
            ['citySlug' => 'soligorsk', 'dealType' => 'rent', 'listingType' => 'apartment', 'price' => 290, 'rooms' => 2, 'area' => 46.0, 'floor' => 4, 'totalFloors' => 9, 'address' => 'ул. Козлова, 28', 'rentTerm' => 'long', 'verified' => false, 'fromOwner' => true, 'hasRenovation' => true, 'hasDeposit' => true, 'utilitiesIncluded' => false, 'noCommission' => false, 'latOffset' => -0.009, 'lngOffset' => 0.006],
            ['citySlug' => 'soligorsk', 'dealType' => 'sale', 'listingType' => 'commercial', 'price' => 125000, 'rooms' => 1, 'area' => 70.0, 'floor' => 1, 'totalFloors' => 2, 'address' => 'пр. Мира, 18', 'rentTerm' => null, 'verified' => true, 'fromOwner' => true, 'hasRenovation' => false, 'hasDeposit' => false, 'utilitiesIncluded' => false, 'noCommission' => true, 'latOffset' => 0.008, 'lngOffset' => 0.01],

            ['citySlug' => 'molodechno', 'dealType' => 'sale', 'listingType' => 'apartment', 'price' => 58000, 'rooms' => 2, 'area' => 50.0, 'floor' => 5, 'totalFloors' => 9, 'address' => 'ул. Великий Гостинец, 51', 'rentTerm' => null, 'verified' => false, 'fromOwner' => true, 'hasRenovation' => true, 'hasDeposit' => false, 'utilitiesIncluded' => false, 'noCommission' => true, 'latOffset' => 0.006, 'lngOffset' => -0.007],
            ['citySlug' => 'molodechno', 'dealType' => 'rent', 'listingType' => 'apartment', 'price' => 250, 'rooms' => 1, 'area' => 33.0, 'floor' => 2, 'totalFloors' => 5, 'address' => 'ул. Янки Купалы, 9', 'rentTerm' => 'daily', 'verified' => true, 'fromOwner' => false, 'hasRenovation' => false, 'hasDeposit' => false, 'utilitiesIncluded' => true, 'noCommission' => true, 'latOffset' => -0.008, 'lngOffset' => 0.005],
            ['citySlug' => 'molodechno', 'dealType' => 'sale', 'listingType' => 'house', 'price' => 112000, 'rooms' => 4, 'area' => 105.0, 'floor' => 1, 'totalFloors' => 2, 'address' => 'ул. Либаво-Роменская, 3', 'rentTerm' => null, 'verified' => true, 'fromOwner' => true, 'hasRenovation' => true, 'hasDeposit' => false, 'utilitiesIncluded' => false, 'noCommission' => false, 'latOffset' => 0.013, 'lngOffset' => 0.012],

            ['citySlug' => 'zhodino', 'dealType' => 'sale', 'listingType' => 'apartment', 'price' => 49000, 'rooms' => 2, 'area' => 45.0, 'floor' => 3, 'totalFloors' => 5, 'address' => 'ул. 50 лет Октября, 12', 'rentTerm' => null, 'verified' => true, 'fromOwner' => true, 'hasRenovation' => false, 'hasDeposit' => false, 'utilitiesIncluded' => false, 'noCommission' => true, 'latOffset' => 0.004, 'lngOffset' => -0.005],
            ['citySlug' => 'zhodino', 'dealType' => 'rent', 'listingType' => 'apartment', 'price' => 230, 'rooms' => 1, 'area' => 32.0, 'floor' => 4, 'totalFloors' => 5, 'address' => 'ул. Рокоссовского, 7', 'rentTerm' => 'long', 'verified' => false, 'fromOwner' => false, 'hasRenovation' => true, 'hasDeposit' => true, 'utilitiesIncluded' => false, 'noCommission' => false, 'latOffset' => -0.006, 'lngOffset' => 0.007],

            ['citySlug' => 'berezino', 'dealType' => 'sale', 'listingType' => 'house', 'price' => 42000, 'rooms' => 3, 'area' => 82.0, 'floor' => 1, 'totalFloors' => 2, 'address' => 'ул. Советская, 27', 'rentTerm' => null, 'verified' => true, 'fromOwner' => true, 'hasRenovation' => true, 'hasDeposit' => false, 'utilitiesIncluded' => false, 'noCommission' => true, 'latOffset' => 0.003, 'lngOffset' => 0.004],
            ['citySlug' => 'mir', 'dealType' => 'rent', 'listingType' => 'house', 'price' => 450, 'rooms' => 3, 'area' => 88.0, 'floor' => 1, 'totalFloors' => 2, 'address' => 'ул. Кирова, 11', 'rentTerm' => 'long', 'verified' => false, 'fromOwner' => true, 'hasRenovation' => false, 'hasDeposit' => true, 'utilitiesIncluded' => true, 'noCommission' => false, 'latOffset' => -0.004, 'lngOffset' => -0.003],
            ['citySlug' => 'motol', 'dealType' => 'sale', 'listingType' => 'house', 'price' => 36000, 'rooms' => 3, 'area' => 76.0, 'floor' => 1, 'totalFloors' => 1, 'address' => 'ул. Центральная, 15', 'rentTerm' => null, 'verified' => true, 'fromOwner' => true, 'hasRenovation' => false, 'hasDeposit' => false, 'utilitiesIncluded' => false, 'noCommission' => true, 'latOffset' => 0.002, 'lngOffset' => 0.003],
            ['citySlug' => 'chechersk', 'dealType' => 'rent', 'listingType' => 'apartment', 'price' => 180, 'rooms' => 2, 'area' => 44.0, 'floor' => 2, 'totalFloors' => 4, 'address' => 'ул. Ленина, 14', 'rentTerm' => 'long', 'verified' => false, 'fromOwner' => false, 'hasRenovation' => true, 'hasDeposit' => false, 'utilitiesIncluded' => true, 'noCommission' => true, 'latOffset' => -0.003, 'lngOffset' => 0.002],
        ];
    }
}
