apiVersion: v1
kind: ConfigMap
metadata:
  name: renlo-config
  namespace: renlo
data:
  APP_ENV: prod
  POSTGRES_DB: renlo
  POSTGRES_USER: renlo
  KAFKA_MESSENGER_DSN: kafka://renlo-kafka:9092
  KAFKA_BROKERS: renlo-kafka:9092
  CORS_ALLOW_ORIGIN: '^https?://(.*\.)?renlo\.(by|local)(:[0-9]+)?$'
  MESSENGER_TRANSPORT_DSN: doctrine://default?auto_setup=0
  MAILER_DSN: null://null
  VITE_API_BASE_URL: ''
  DEFAULT_URI: https://renlo.by
